
set_property PACKAGE_PIN M7 [get_ports {ADC_CSB[1]}]
set_property PACKAGE_PIN M6 [get_ports {ADC_SCLK[1]}]
set_property PACKAGE_PIN N9 [get_ports {ADC_SDIO[1]}]
set_property PACKAGE_PIN N1 [get_ports {ADC_D_N[0]}]
set_property PACKAGE_PIN R1 [get_ports {ADC_D_N[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_CSB[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SCLK[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_P[1]}]
set_property PACKAGE_PIN P6 [get_ports {ADC_CLK_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SDIO[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[2]}]
set_property PACKAGE_PIN N3 [get_ports {ADC_D_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[1]}]
set_property PACKAGE_PIN P5 [get_ports {ADC_DCO_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_P[1]}]
set_property PACKAGE_PIN R6 [get_ports {ADC_FCO_P[1]}]
set_property PACKAGE_PIN T5 [get_ports {ADC_D_P[5]}]
set_property PACKAGE_PIN R3 [get_ports {ADC_D_P[3]}]
set_property PACKAGE_PIN U2 [get_ports {ADC_D_P[6]}]
set_property PACKAGE_PIN T3 [get_ports {ADC_D_P[4]}]
set_property PACKAGE_PIN U5 [get_ports {ADC_D_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[7]}]

set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_P[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_N[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_N[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_N[4]}]
set_property PACKAGE_PIN AN7 [get_ports {ADC_CLK_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_N[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports NIM_OUT]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_CSB[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_CSB[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_CSB[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_CSB[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_CSB[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_CSB[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_CSB[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[63]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[63]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[62]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[62]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[61]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[61]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[60]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[60]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[59]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[59]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[58]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[58]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[57]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[57]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[56]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[56]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[55]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[55]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[54]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[54]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[53]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[53]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[52]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[52]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[51]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[51]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[50]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[50]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[49]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[49]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[48]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[48]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[47]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[47]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[46]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[46]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[45]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[45]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[44]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[44]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[43]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[43]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[42]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[42]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[41]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[41]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[40]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[40]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[39]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[39]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[38]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[38]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[37]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[37]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[36]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[36]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[35]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[35]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[34]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[34]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[33]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[33]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[32]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[32]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[31]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[31]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[30]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[30]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[29]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[29]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[28]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[28]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[27]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[27]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[26]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[26]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[25]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[25]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[24]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[24]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[23]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[23]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[22]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[22]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[21]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[21]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[20]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[20]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[19]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[19]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[18]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[18]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[17]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[17]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[16]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[16]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_N[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_P[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_P[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_N[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_N[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_N[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCO_N[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_P[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_N[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_N[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_N[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCO_N[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SCLK[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SCLK[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SCLK[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SCLK[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SCLK[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SCLK[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SCLK[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SDIO[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SDIO[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SDIO[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SDIO[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SDIO[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SDIO[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADC_SDIO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIP_SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIP_SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIP_SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIP_SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NIM_INn[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NIM_INn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NIM_INn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NIM_INn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X_LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X_LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X_LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {X_LED[0]}]
set_property PACKAGE_PIN W10 [get_ports {ADC_CSB[2]}]
set_property PACKAGE_PIN Y10 [get_ports {ADC_SCLK[2]}]
set_property PACKAGE_PIN V9 [get_ports {ADC_SDIO[2]}]
set_property PACKAGE_PIN W6 [get_ports {ADC_CLK_P[2]}]
set_property PACKAGE_PIN W1 [get_ports {ADC_D_P[8]}]
set_property PACKAGE_PIN Y3 [get_ports {ADC_D_P[9]}]
set_property PACKAGE_PIN V3 [get_ports {ADC_FCO_P[2]}]
set_property PACKAGE_PIN W5 [get_ports {ADC_DCO_P[2]}]
set_property PACKAGE_PIN AA5 [get_ports {ADC_D_P[11]}]
set_property PACKAGE_PIN AB5 [get_ports {ADC_D_P[13]}]
set_property PACKAGE_PIN AB2 [get_ports {ADC_D_P[12]}]
set_property PACKAGE_PIN AA3 [get_ports {ADC_D_P[10]}]
set_property PACKAGE_PIN AC2 [get_ports {ADC_D_P[14]}]
set_property PACKAGE_PIN AC4 [get_ports {ADC_D_P[15]}]
set_property PACKAGE_PIN AG1 [get_ports {ADC_D_P[19]}]
set_property PACKAGE_PIN AD1 [get_ports {ADC_D_P[23]}]
set_property PACKAGE_PIN AH2 [get_ports {ADC_D_P[17]}]
set_property PACKAGE_PIN AE2 [get_ports {ADC_D_P[22]}]
set_property PACKAGE_PIN AF3 [get_ports {ADC_D_P[21]}]
set_property PACKAGE_PIN AH3 [get_ports {ADC_D_P[18]}]
set_property PACKAGE_PIN AF4 [get_ports {ADC_D_P[20]}]
set_property PACKAGE_PIN AD5 [get_ports {ADC_FCO_P[3]}]
set_property PACKAGE_PIN AH4 [get_ports {ADC_D_P[16]}]
set_property PACKAGE_PIN AG6 [get_ports {ADC_CLK_P[3]}]
set_property PACKAGE_PIN AE5 [get_ports {ADC_DCO_P[3]}]
set_property PACKAGE_PIN AD9 [get_ports {ADC_CSB[3]}]
set_property PACKAGE_PIN AE8 [get_ports {ADC_SDIO[3]}]
set_property PACKAGE_PIN AD8 [get_ports {ADC_SCLK[3]}]
set_property PACKAGE_PIN AN1 [get_ports {ADC_D_P[26]}]
set_property PACKAGE_PIN AK2 [get_ports {ADC_D_N[24]}]
set_property PACKAGE_PIN AL2 [get_ports {ADC_D_N[25]}]
set_property PACKAGE_PIN AN3 [get_ports {ADC_D_P[27]}]
set_property PACKAGE_PIN AN4 [get_ports {ADC_D_P[28]}]
set_property PACKAGE_PIN AP6 [get_ports {ADC_D_N[29]}]
set_property PACKAGE_PIN AP11 [get_ports {ADC_D_N[31]}]
set_property PACKAGE_PIN AN8 [get_ports {ADC_FCO_P[4]}]
set_property PACKAGE_PIN AN9 [get_ports {ADC_D_P[30]}]
set_property PACKAGE_PIN AM6 [get_ports {ADC_SDIO[4]}]
set_property PACKAGE_PIN AJ6 [get_ports {ADC_DCO_P[4]}]
set_property PACKAGE_PIN AL5 [get_ports {ADC_SCLK[4]}]
set_property PACKAGE_PIN AL4 [get_ports {ADC_CSB[4]}]
set_property PACKAGE_PIN AL34 [get_ports {ADC_D_N[38]}]
set_property PACKAGE_PIN AJ33 [get_ports {ADC_D_P[39]}]
set_property PACKAGE_PIN AN34 [get_ports {ADC_D_P[37]}]
set_property PACKAGE_PIN AN33 [get_ports {ADC_D_P[36]}]
set_property PACKAGE_PIN AL32 [get_ports {ADC_FCO_P[5]}]
set_property PACKAGE_PIN AM31 [get_ports {ADC_SCLK[5]}]
set_property PACKAGE_PIN AN32 [get_ports {ADC_SDIO[5]}]
set_property PACKAGE_PIN AN31 [get_ports {ADC_D_P[35]}]
set_property PACKAGE_PIN AL30 [get_ports {ADC_DCO_P[5]}]
set_property PACKAGE_PIN AP29 [get_ports {ADC_D_P[34]}]
set_property PACKAGE_PIN AN28 [get_ports {ADC_D_P[33]}]
set_property PACKAGE_PIN AM29 [get_ports {ADC_CLK_P[5]}]
set_property PACKAGE_PIN AP25 [get_ports {ADC_D_P[32]}]
set_property PACKAGE_PIN AF34 [get_ports {ADC_D_N[43]}]
set_property PACKAGE_PIN AD33 [get_ports {ADC_D_P[47]}]
set_property PACKAGE_PIN AH33 [get_ports {ADC_D_P[41]}]
set_property PACKAGE_PIN AE33 [get_ports {ADC_D_P[45]}]
set_property PACKAGE_PIN AG32 [get_ports {ADC_D_P[42]}]
set_property PACKAGE_PIN AE32 [get_ports {ADC_D_P[44]}]
set_property PACKAGE_PIN AD31 [get_ports {ADC_D_P[46]}]
set_property PACKAGE_PIN AD30 [get_ports {ADC_CLK_P[6]}]
set_property PACKAGE_PIN AD28 [get_ports {ADC_FCO_P[6]}]
set_property PACKAGE_PIN AG31 [get_ports {ADC_D_P[40]}]
set_property PACKAGE_PIN AG29 [get_ports {ADC_DCO_P[6]}]
set_property PACKAGE_PIN AC26 [get_ports {ADC_CSB[6]}]
set_property PACKAGE_PIN AC27 [get_ports {ADC_SCLK[6]}]
set_property PACKAGE_PIN AG27 [get_ports {ADC_SDIO[6]}]
set_property PACKAGE_PIN W28 [get_ports {ADC_FCO_P[7]}]
set_property PACKAGE_PIN V31 [get_ports {ADC_CLK_P[7]}]
set_property PACKAGE_PIN W33 [get_ports {ADC_D_P[54]}]
set_property PACKAGE_PIN V33 [get_ports {ADC_D_P[55]}]
set_property PACKAGE_PIN Y32 [get_ports {ADC_D_P[53]}]
set_property PACKAGE_PIN W30 [get_ports {ADC_DCO_P[7]}]
set_property PACKAGE_PIN AB31 [get_ports {ADC_D_P[50]}]
set_property PACKAGE_PIN AC33 [get_ports {ADC_D_P[49]}]
set_property PACKAGE_PIN AA32 [get_ports {ADC_D_P[52]}]
set_property PACKAGE_PIN AC31 [get_ports {ADC_D_P[48]}]
set_property PACKAGE_PIN AA34 [get_ports {ADC_D_N[51]}]
set_property PACKAGE_PIN AC29 [get_ports {ADC_CSB[7]}]
set_property PACKAGE_PIN AA29 [get_ports {ADC_SCLK[7]}]
set_property PACKAGE_PIN AB29 [get_ports {ADC_SDIO[7]}]
set_property PACKAGE_PIN N27 [get_ports {ADC_CSB[8]}]
set_property PACKAGE_PIN N28 [get_ports {ADC_SCLK[8]}]
set_property PACKAGE_PIN T28 [get_ports {ADC_SDIO[8]}]
set_property PACKAGE_PIN N29 [get_ports {ADC_FCO_P[8]}]
set_property PACKAGE_PIN U30 [get_ports {ADC_DCO_P[8]}]
set_property PACKAGE_PIN M30 [get_ports {ADC_D_P[62]}]
set_property PACKAGE_PIN R31 [get_ports {ADC_CLK_P[8]}]
set_property PACKAGE_PIN N31 [get_ports {ADC_D_P[60]}]
set_property PACKAGE_PIN U31 [get_ports {ADC_D_P[56]}]
set_property PACKAGE_PIN T32 [get_ports {ADC_D_P[58]}]
set_property PACKAGE_PIN N32 [get_ports {ADC_D_P[61]}]
set_property PACKAGE_PIN T33 [get_ports {ADC_D_P[59]}]
set_property PACKAGE_PIN N34 [get_ports {ADC_D_P[63]}]
set_property PACKAGE_PIN U34 [get_ports {ADC_D_P[57]}]
set_property PACKAGE_PIN J24 [get_ports {X_LED[0]}]
set_property PACKAGE_PIN H24 [get_ports {X_LED[1]}]
set_property PACKAGE_PIN H27 [get_ports {X_LED[2]}]
set_property PACKAGE_PIN G27 [get_ports {X_LED[3]}]
set_property PACKAGE_PIN J28 [get_ports OSC50M]
set_property IOSTANDARD LVCMOS33 [get_ports OSC50M]
set_property PACKAGE_PIN J29 [get_ports {NIM_INn[1]}]
set_property PACKAGE_PIN H29 [get_ports {NIM_INn[2]}]
set_property PACKAGE_PIN K30 [get_ports {NIM_INn[3]}]
set_property PACKAGE_PIN J30 [get_ports {NIM_INn[4]}]
set_property PACKAGE_PIN G32 [get_ports NIM_OUT]
set_property PACKAGE_PIN H33 [get_ports {DIP_SW[0]}]
set_property PACKAGE_PIN G34 [get_ports {DIP_SW[1]}]
set_property PACKAGE_PIN L32 [get_ports {DIP_SW[2]}]
set_property PACKAGE_PIN K32 [get_ports {DIP_SW[3]}]
set_property PACKAGE_PIN L12 [get_ports EEPROM_SK]
set_property PACKAGE_PIN K12 [get_ports EEPROM_CS]
set_property PACKAGE_PIN G10 [get_ports {ETH_TXD[1]}]
set_property PACKAGE_PIN G9 [get_ports {ETH_TXD[2]}]
set_property PACKAGE_PIN K11 [get_ports EEPROM_DI]
set_property PACKAGE_PIN J11 [get_ports EEPROM_DO]
set_property PACKAGE_PIN H11 [get_ports ETH_MDIO]
set_property PACKAGE_PIN G11 [get_ports {ETH_TXD[0]}]
set_property PACKAGE_PIN J8 [get_ports ETH_COL]
set_property PACKAGE_PIN H9 [get_ports ETH_MDC]
set_property PACKAGE_PIN H8 [get_ports {ETH_TXD[3]}]
set_property PACKAGE_PIN K8 [get_ports ETH_CRS]
set_property PACKAGE_PIN G7 [get_ports {ETH_TXD[4]}]
set_property PACKAGE_PIN G6 [get_ports {ETH_TXD[5]}]
set_property PACKAGE_PIN F3 [get_ports {ETH_TXD[6]}]
set_property PACKAGE_PIN F2 [get_ports {ETH_TXD[7]}]
set_property PACKAGE_PIN H3 [get_ports ETH_TX_ER]
set_property PACKAGE_PIN J4 [get_ports ETH_TX_EN]
set_property PACKAGE_PIN J3 [get_ports {ETH_RXD[4]}]
set_property PACKAGE_PIN H2 [get_ports {ETH_RXD[6]}]
set_property PACKAGE_PIN K1 [get_ports {ETH_RXD[3]}]
set_property PACKAGE_PIN J1 [get_ports {ETH_RXD[5]}]
set_property PACKAGE_PIN H1 [get_ports {ETH_RXD[7]}]
set_property PACKAGE_PIN M2 [get_ports {ETH_RXD[0]}]
set_property PACKAGE_PIN L2 [get_ports {ETH_RXD[1]}]
set_property PACKAGE_PIN K3 [get_ports ETH_RSTn]
set_property PACKAGE_PIN K2 [get_ports {ETH_RXD[2]}]
set_property PACKAGE_PIN G5 [get_ports ETH_RX_CLK]
set_property PACKAGE_PIN K7 [get_ports ETH_RX_ER]
set_property PACKAGE_PIN K6 [get_ports ETH_RX_DV]
set_property PACKAGE_PIN H7 [get_ports ETH_TX_CLK]
set_property PACKAGE_PIN AK32 [get_ports {ADC_CSB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_CS]
set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_DI]
set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_DO]
set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_SK]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_COL]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_CRS]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_MDC]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_MDIO]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RSTn]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RX_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RX_DV]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RX_ER]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TX_EN]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TX_ER]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TX_CLK]

set_property PULLUP true [get_ports {DIP_SW[3]}]
set_property PULLUP true [get_ports {DIP_SW[2]}]
set_property PULLUP true [get_ports {DIP_SW[1]}]
set_property PULLUP true [get_ports {DIP_SW[0]}]

set_property PULLUP true [get_ports {ADC_SDIO[8]}]
set_property PULLUP true [get_ports {ADC_SDIO[7]}]
set_property PULLUP true [get_ports {ADC_SDIO[6]}]
set_property PULLUP true [get_ports {ADC_SDIO[5]}]
set_property PULLUP true [get_ports {ADC_SDIO[4]}]
set_property PULLUP true [get_ports {ADC_SDIO[3]}]
set_property PULLUP true [get_ports {ADC_SDIO[2]}]
set_property PULLUP true [get_ports {ADC_SDIO[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports DAC_CLKI]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_SDI]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_SDO]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_STRI]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_STRO]
set_property PACKAGE_PIN L23 [get_ports DAC_CLKI]
set_property PACKAGE_PIN M24 [get_ports DAC_SDI]
set_property PACKAGE_PIN L24 [get_ports DAC_STRI]
set_property PACKAGE_PIN K23 [get_ports DAC_SDO]
set_property PACKAGE_PIN J23 [get_ports DAC_STRO]


set_property IOSTANDARD LVCMOS33 [get_ports GTX_CLK]
set_property PACKAGE_PIN H4 [get_ports GTX_CLK]

set_property PACKAGE_PIN J25 [get_ports TP_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports TP_OUT]

set_property PACKAGE_PIN H12 [get_ports ETH_1000_LED]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_1000_LED]

create_clock -period 8.333 -name {ADC_DCO_P[1]} -waveform {0.000 4.167} [get_ports {ADC_DCO_P[1]}]
create_clock -period 8.333 -name {ADC_DCO_P[2]} -waveform {0.000 4.167} [get_ports {ADC_DCO_P[2]}]
create_clock -period 8.333 -name {ADC_DCO_P[3]} -waveform {0.000 4.167} [get_ports {ADC_DCO_P[3]}]
create_clock -period 8.333 -name {ADC_DCO_P[4]} -waveform {0.000 4.167} [get_ports {ADC_DCO_P[4]}]
create_clock -period 8.333 -name {ADC_DCO_P[5]} -waveform {0.000 4.167} [get_ports {ADC_DCO_P[5]}]
create_clock -period 8.333 -name {ADC_DCO_P[6]} -waveform {0.000 4.167} [get_ports {ADC_DCO_P[6]}]
create_clock -period 8.333 -name {ADC_DCO_P[7]} -waveform {0.000 4.167} [get_ports {ADC_DCO_P[7]}]
create_clock -period 8.333 -name {ADC_DCO_P[8]} -waveform {0.000 4.167} [get_ports {ADC_DCO_P[8]}]
create_clock -period 8.000 -name ETH_RX_CLK -waveform {0.000 4.000} [get_ports ETH_RX_CLK]
create_clock -period 8.000 -name ETH_TX_CLK -waveform {0.000 4.000} [get_ports ETH_TX_CLK]
create_clock -period 20.000 -name {NIM_INn[4]} -waveform {0.000 10.000} [get_ports {NIM_INn[4]}]
create_clock -period 20.000 -name OSC50M -waveform {0.000 10.000} [get_ports OSC50M]

set_false_path -through [get_nets SiTCP/SiTCP/SiTCP_INT/SiTCP_INT_REG/reg*]
set_false_path -through [get_nets SiTCP/SiTCP/BBT_SiTCP_RST/resetReq*]
set_false_path -through [get_nets SiTCP/SiTCP/GMII/GMII_TXBUF/memRdReq*]
set_false_path -through [get_nets SiTCP/SiTCP/GMII/GMII_TXBUF/orRdAct*]
set_false_path -through [get_nets SiTCP/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr*]
set_false_path -through [get_nets SiTCP/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr*]
set_false_path -through [get_nets SiTCP/SiTCP/GMII/GMII_TXBUF/muxEndTgl]
set_false_path -through [get_nets SiTCP/SiTCP/GMII/GMII_RXBUF/cmpWrAddr*]

set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[1]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[1]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[2]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[2]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[3]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[3]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[4]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[4]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[5]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[5]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[6]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[6]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[7]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[7]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[8]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks {ADC_DCO_P[8]}] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks ETH_RX_CLK] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks ETH_RX_CLK] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks ETH_RX_CLK] -group [get_clocks ETH_TX_CLK]
set_clock_groups -asynchronous -group [get_clocks ETH_RX_CLK] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT1] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks ETH_RX_CLK] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT1] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks ETH_TX_CLK] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks ETH_TX_CLK] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks ETH_TX_CLK] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT1] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks ETH_TX_CLK] -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT1] -filter {IS_GENERATED && MASTER_CLOCK == OSC50M}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}] -group [get_clocks ETH_RX_CLK]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins instance_name/inst/mmcm_adv_inst/CLKOUT0] -filter {IS_GENERATED && MASTER_CLOCK == NIM_INn[4]}] -group [get_clocks ETH_TX_CLK]
set_clock_groups -asynchronous -group [get_clocks OSC50M] -group [get_clocks {NIM_INn[4]}]
set_clock_groups -asynchronous -group [get_clocks {NIM_INn[4]}] -group [get_clocks OSC50M]
